apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: balloon-priority
value: -100
preemptionPolicy: Never
globalDefault: false
description: "Balloon Pod Priority."

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: balloon-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: balloon
  template:
    metadata:
      labels:
        app: balloon
    spec:
      priorityClassName: balloon-priority
      terminationGracePeriodSeconds: 0
      containers:
      - name: alpine
        image: alpine:latest
        command: ["sleep"]
        args: ["infinity"]
        resources:
            requests:
              cpu: 1
              memory: 1G
