apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkggcp-k8s-ig-bsc
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.0-alpine
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: pkggcp-k8s-ig-bsc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: nginx
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pkggcp-k8s-ig-bsc
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  labels:
    app: nginx
spec:
  rules:
    - http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: pkggcp-k8s-bc-hl
              port:
                number: 80
