apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkggcp-k8s-ig-bsc
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.0-alpine
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: pkggcp-k8s-ig-bsc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: nginx
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  labels:
    app: nginx
  name: pkggcp-k8s-ig-bsc
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: pkggcp-k8s-bc-hl
            servicePort: 80
          path: /*
