apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.46-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          # mountPath: "/var/tmp/hogehoge"  ## moutPath の名前のディレクトリが生成され、name の名前のファイル(シンボリックリンク)が生成される
          mountPath: "/usr/local/apache2/conf/corporate"  ## moutPath の名前のディレクトリが生成され、name の名前のファイル(シンボリックリンク)が生成される
          # readOnly: true
      volumes:
        - name: config
          configMap:
            name: apache-configmap
            items:                           # key と path が一致しているので書く必要は無い
            - key: "rewrite.conf"
              # path: "conf/extra/rewrite.conf"
              path: "rewrite.conf"

---

apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  type: LoadBalancer
  selector:
    app: apache
  ports:
  - name: apache
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-configmap
data:
  rewrite.conf: |
    <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^/$ https://www.google.com [R=301,L]   ## / にアクセスすると Google に 301 リダイレクトする
    </IfModule>
