steps:
  - id: 'Check Deprecations'
    name: 'ubuntu:latest'
    entrypoint: bash
    dir: ${_MANIFEST_DIR}
    args:
      - -c
      - |
        set -eu
        apt update && apt install -y wget
        wget https://github.com/FairwindsOps/pluto/releases/download/v${_PLUTO_VERSION}/pluto_${_PLUTO_VERSION}_linux_amd64.tar.gz
        tar -zxvf pluto_${_PLUTO_VERSION}_linux_amd64.tar.gz
        chmod +x pluto
        ./pluto detect-files --output wide --directory ./

substitutions:
  _MANIFEST_DIR: 'builds/pluto'
  _PLUTO_VERSION: '5.8.0'            ### https://github.com/FairwindsOps/pluto/releases
