apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddns-vpc-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clouddns-vpc-a
  template:
    metadata:
      labels:
        app: clouddns-vpc-a
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.0-alpine
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: clouddns-vpc-a
spec:
  type: ClusterIP
  selector:
    app: clouddns-vpc-a
  ports:
  - name: nginx
    port: 80
    targetPort: 80
