apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddns-test-a
  # labels:
  #   app: clouddns-test-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clouddns-test-a
  template:
    metadata:
      labels:
        app: clouddns-test-a
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.0-alpine
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: clouddns-test-a
  # labels:
  #   app: clouddns-test-a
spec:
  type: ClusterIP
  selector:
    app: clouddns-test-a
  ports:
  - name: nginx
    port: 80
    targetPort: 80
