steps:
  - id: "Check cURL"
    name: 'python:3.9.2-alpine3.12'
    # entrypoint: ash
    # dir: 'scripts'
    args: ["--version"]

#   - id: "run local script"
#     name: 'alpine:edge'
#     entrypoint: ash
#     args: ["./check-curl.sh"]
# 
#   - id: "Check gcloud cli"
#     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     args: ["gcloud", "version"]
# 
#   - id: "gcloud auth 1"
#     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'gcloud'
#     args: ["auth", "list"]
# 
#   - id: "gcloud auth 2"
#     name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     args: ["gcloud", "auth", "list"]
