steps:
  - id: "Check Python Version"
    name: 'python:3.9.2-alpine3.12'
    # entrypoint: ash
    # dir: 'scripts'
    args: ["python3", "--version"]

  - id: "Check Global IP Address"
    name: 'python:3.9.2-alpine3.12'
    # entrypoint: ash
    dir: 'python/chk_global_ip'
    args:
    args: ["python3", "main.py"]

  - id: "Check Flask on Public Container"
    name: 'python:3.9.2-alpine3.12'
    entrypoint: ash
    dir: 'python/flask'
    args:
      - -c
      - |
        pip3 install -r requirements.txt
        FLASK_APP=main.py FLASK_DEBUG=1 nohup flask run --host='0.0.0.0' --port=5000 >out.log 2>err.log &
        ps
        apk update && apk add curl
        curl 0.0.0.0:5000
