#
# roles/common/tasks/main.yml
#

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
