steps:
  - id: 'Deploy Image to GCR'
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build -f Dockerfile . --tag=gcr.io/${PROJECT_ID}/${_container_image_name}:${COMMIT_SHA}
        docker build -f Dockerfile . --tag=gcr.io/${PROJECT_ID}/${_container_image_name}:latest
        docker push gcr.io/${PROJECT_ID}/${_container_image_name}:${COMMIT_SHA}
        docker push gcr.io/${PROJECT_ID}/${_container_image_name}:latest
  - id: 'Deploy Manifest to GKE Cluster'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta container clusters get-credentials ${_cluster_name} --zone ${_your_gke_cluster_zone} --project ${PROJECT_ID}
        # kubectl get node
        sed -i -e "s/_COMMIT_SHA/$COMMIT_SHA/g" k8s.yaml
        kubectl apply -f k8s.yaml
        kubectl get pod
