steps:

  - id: '[Terraform] Check Terraform Version'
    name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
    entrypoint: ash
    args:
      - -c
      - |
        apk update && apk add curl jq
        export _this_tf_ver=$(terraform version | awk 'NR==1 {print $2}')
        export _latest_tf_ver=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | jq -r .tag_name)
        if [ "${_this_tf_ver}" == "${_latest_tf_ver}" ]; then echo '実行している Terraform の Version は最新版のようです!! :)' ; else echo '実行している Terraform の Version は最新版ではありません。 Terraform の Version を確認してください。---> https://github.com/hashicorp/terraform/releases' && exit 1 ; fi
#   - id: '[Terraform] Init'
#     name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
#     args: ["init"]
#   - id: '[Terraform] Validate'
#     name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
#     args: ["validate"]
#   - id: '[Terraform] Plan'
#     name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
#     args: ["plan"]
#   - id: '[Terraform] Apply'
#     name: "hashicorp/terraform:${_TERRAFORM_VERSION}"
#     args: ["apply", "-auto-approve"]

substitutions:
  _TERRAFORM_VERSION: '1.2.2'
