apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplesesafi-dep
  # labels:
  #   app: samplesesafi-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplesesafi-dep
  template:
    metadata:
      labels:
        app: samplesesafi-dep
    spec:
      containers:
      - name: samplesesafi-dep
        image: iganarix/code-labo-python:latest
        ports:
        - containerPort: 5000

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: samplesesafi-bkc
spec:
  sessionAffinity:
    affinityType: "CLIENT_IP"

---

apiVersion: v1
kind: Service
metadata:
  name: samplesesafi-srv
  # labels:
  #   app: samplesesafi-srv
  annotations:
    cloud.google.com/backend-config: '{
      "default": "samplesesafi-bkc"
    }'
spec:
  type: NodePort
  # type: ClusterIP
  selector:
    app: samplesesafi-dep
  ports:
  - name: samplesesafi-srv
    port: 80
    targetPort: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplesesafi-igr
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  # labels:
  #   app: samplesesafi-igr
spec:
  rules:
    - http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: samplesesafi-srv
              port:
                number: 80
