apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-config-sample
  namespace: default
spec:
  securityPolicy:
    name: "ip-addr-whitelist"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
    env: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: sample
  template:
    metadata:
      labels:
        app: nginx
        env: sample
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx
    env: sample
  annotations:
    beta.cloud.google.com/backend-config: '{
      "ports": {
        "8080":"backend-config-sample"
      }
    }'
spec:
  type: NodePort
  selector:
    app: nginx
    env: sample
  ports:
    - port: 8080
      targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  labels:
    app: nginx
    env: sample
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: nginx-service
          servicePort: 8080
