apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-pkg-gcp
  namespace: default
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - asia-northeast1-a
    - asia-northeast1-b
    - asia-northeast1-c

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pkg-gcp
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: sc-pkg-gcp

---

apiVersion: v1
kind: Pod
metadata:
  name: pkg-gcp
  namespace: default
spec:
  volumes:
    - name: pkg-gcp-storage
      persistentVolumeClaim:
        claimName: pvc-pkg-gcp
  containers:
    - name: pkg-gcp-container
      image: nginx:1.21.4
      ports:
        - name: "http-serger"
          containerPort: 80
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 300m
          memory: 500m
      volumeMounts:
        - name: pkg-gcp-storage
          mountPath: "/usr/share/nginx/html"
