apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.25
        imagePullPolicy: Always
        args:
          - "--default-authentication-plugin=mysql_native_password"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: wReo+y7QH9aIH6jPWdm3Omv8a8xJ0CHO
        - name: MYSQL_DATABASE
          value: my_database
        - name: MYSQL_USER
          value: my_dbadmin
        - name: MYSQL_PASSWORD
          value: eq02lOu7
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: "800m"
          requests:
            cpu : "600m"
        volumeMounts:
        - name:  mysql-pvc-tpl
          mountPath: /var/lib/mysql
          subPath: mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc-tpl
      labels:
        app: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  # labels:
  #   app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: mysql
