apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-svc
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        imagePullPolicy: Always
        ports:
        - name: nginx
          containerPort: 80
        resources:
          limits:
            cpu: "800m"
          requests:
            cpu : "600m"
        volumeMounts:
        - name:  nginx-pvc-tpl
          # mountPath: /var/tmp/nginx
          mountPath: /usr/share/nginx/html
          subPath: html
  volumeClaimTemplates:
  - metadata:
      name: nginx-pvc-tpl
      labels:
        app: nginx
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  # labels:
  #   app: nginx
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: nginx
  ports:
    - port: 80
